// Generated by https://quicktype.io

export interface PlaceList {
    geometry:       Geometry;
    icon:           string;
    id:             string;
    name:           string;
    opening_hours?: OpeningHours;
    photos?:        Photo[];
    place_id:       string;
    plus_code:      PlusCode;
    rating:         number;
    reference:      string;
    scope:          string;
    types:          Type[];
    vicinity:       string;
}

export interface Geometry {
    location: Location;
    viewport: Viewport;
}

export interface Location {
    lat: number;
    lng: number;
}

export interface Viewport {
    northeast: Location;
    southwest: Location;
}

export interface OpeningHours {
    open_now: boolean;
}

export interface Photo {
    height:            number;
    html_attributions: string[];
    photo_reference:   string;
    width:             number;
}

export interface PlusCode {
    compound_code: string;
    global_code:   string;
}

export enum Type {
    Doctor = "doctor",
    Health = "health",
    Hospital = "hospital",
    Pharmacy = "pharmacy",
}
